[package]
name = "rlviser"
version = "0.9.2"
edition = "2024"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_egui = {
  version = "0.39.0",
  default-features = false,
  features = ["default_fonts", "render"]
}
bevy_framepace = { version = "0.21", default-features = false }
bevy_vector_shapes = "0.12"
bincode = "2.0"
byteorder = "1.4.3"
crossbeam-channel = "0.5.12"
image = { version = "0.25.1", default-features = false, features = ["tga"] }
include-flate = "0.3.0"
itertools = "0.14.0"
itoa = "1.0.15"
planus = { git = "https://github.com/swz-git/planus", rev = "a0b1fbf" }
rust_search = "2.1.0"
rustc-hash = "2.1.2"
serde = { version = "1.0.160", features = ["derive", "rc"] }
serde_json = "1.0.96"
thiserror = "2.0"
tracing = { version = "*", features = ["release_max_level_error"] }
walkdir = "2.3.3"
zip = "8.0.0"

[dependencies.bevy]
version = "0.18.1"
default-features = false
features = [
  "default_font",
  "bevy_asset",
  "bevy_camera",
  "bevy_color",
  "bevy_core_pipeline",
  "bevy_gizmos",
  "bevy_image",
  "bevy_input_focus",
  "bevy_light",
  "bevy_log",
  "bevy_mesh",
  "bevy_pbr",
  "bevy_picking",
  "bevy_render",
  "bevy_shader",
  "bevy_state",
  "bevy_text",
  "bevy_ui",
  "bevy_ui_render",
  "bevy_window",
  "bevy_winit",
  "mesh_picking",
  "std",
  "tga",
  "wayland",
  "x11",
]

[build-dependencies]
planus-codegen = { git = "https://github.com/swz-git/planus", rev = "a0b1fbf" }
planus-translation = {
  git = "https://github.com/swz-git/planus",
  rev = "a0b1fbf"
}
planus-types = { git = "https://github.com/swz-git/planus", rev = "a0b1fbf" }

[features]
default = ["bevy/dynamic_linking"]
full_load = []
team_goal_barriers = []
threaded = ["bevy/multi_threaded"]

[lints.clippy]
all = "warn"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.release]
strip = true
lto = true
panic = "abort"

[profile.release-with-debug]
inherits = "release"
debug = true
strip = false

[profile.tiny]
inherits = "release"
opt-level = "s"
